// <auto-generated />
using System;
using EnterpriseMobileApp_ASS1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseMobileApp_ASS1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240508004134_fav")]
    partial class fav
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnterpriseMobileApp_ASS1.Models.Favourite_Store", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("store_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("store_id");

                    b.HasIndex("user_id");

                    b.ToTable("Favourite", (string)null);
                });

            modelBuilder.Entity("EnterpriseMobileApp_ASS1.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("StudentId");

                    b.ToTable("Store", (string)null);
                });

            modelBuilder.Entity("EnterpriseMobileApp_ASS1.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("EnterpriseMobileApp_ASS1.Models.Favourite_Store", b =>
                {
                    b.HasOne("EnterpriseMobileApp_ASS1.Models.Store", "store")
                        .WithMany()
                        .HasForeignKey("store_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterpriseMobileApp_ASS1.Models.Student", "student")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("store");

                    b.Navigation("student");
                });

            modelBuilder.Entity("EnterpriseMobileApp_ASS1.Models.Store", b =>
                {
                    b.HasOne("EnterpriseMobileApp_ASS1.Models.Store", null)
                        .WithMany("favourites")
                        .HasForeignKey("StoreId");

                    b.HasOne("EnterpriseMobileApp_ASS1.Models.Student", null)
                        .WithMany("favourites")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("EnterpriseMobileApp_ASS1.Models.Store", b =>
                {
                    b.Navigation("favourites");
                });

            modelBuilder.Entity("EnterpriseMobileApp_ASS1.Models.Student", b =>
                {
                    b.Navigation("favourites");
                });
#pragma warning restore 612, 618
        }
    }
}
